#undef BOOST_PP_VARIADICS
#undef $time_label
#undef $time_delta
#undef $def_gen_args
#undef $def
#undef $fun_gen_args
#undef $def_local
#undef $in
#undef $ex
#undef $inl
#undef $exl
#undef $inr
#undef $exr
#undef $arguments_enable_postfix_form
#undef $returning
#undef $repeat
#undef $alias
#undef $typedef_enable_generic_accessor
#undef $end
#undef $type
#undef $self
#undef $constructor_argument_declaration_
#undef $constructor_argument_initialization_
#undef $constructor
#undef $setter
#undef $getter
#undef $writeonly
#undef $readonly
#undef $readwrite
