#undef $time_label
#undef $time_delta
#undef $def_gen_args
#undef $def_attributed
#undef $def
#undef $def_s
#undef $fun_gen_args
#undef $def_local
#undef $in
#undef $ex
#undef $inl
#undef $exl
#undef $inr
#undef $exr
#undef auto$in
#undef auto$ex
#undef auto$inl
#undef auto$exl
#undef auto$inr
#undef auto$exr
#undef $arguments_enable_postfix_form
#undef $returning
#undef $main
#undef $repeat
#undef $alias
#undef $typedef_enable_generic_accessor
#undef $end
#undef $type
#undef $obj_inheritance_routine
#undef $obj_parent_aliasing_routine
#undef $obj
#undef $aliasing
#undef $interface
#undef $internal
#undef $protected
#undef $self
#undef $self$ex
#undef $self$in
#undef $constructor_argument_declaration_
#undef $constructor_argument_initialization_
#undef $constructor
#undef $constructor_inherit
#undef $setter
#undef $getter
#undef $writeonly
#undef $readonly
#undef $readwrite
#undef BOOST_PP_VARIADICS
